version: "3.8"

services:
  mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: afiliados
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"

  backend:
    build:
      context: ./backend-laravel
      dockerfile: ../docker/php/Dockerfile
    container_name: backend
    volumes:
      - ./backend-laravel:/var/www/html
    depends_on:
      - mysql
      - mongo
    networks:
      - app

  nodeapi:
    image: node:20
    container_name: nodeapi
    working_dir: /app
    volumes:
      - ./backend-node:/app
    command: bash -c "npm install && npm run dev"
    ports:
      - "3001:3001"
    depends_on:
      - mongo
    networks:
      - app

  frontend:
    image: node:20
    container_name: frontend
    working_dir: /app
    volumes:
      - ./frontend-react:/app
    command: bash -c "npm install && npm run dev -- --host"
    ports:
      - "5173:5173"
    networks:
      - app

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./backend-laravel:/var/www/html
    depends_on:
      - backend
      - frontend
      - nodeapi
    networks:
      - app

networks:
  app:
    driver: bridge

volumes:
  mysql_data:
  mongo_data:
